modLoader = "javafml"
loaderVersion = "[0,)"
license = "All Rights Reserved"

[[mods]]
modId = "travelers_lantern"
version = "${version}"
displayName = "${name}"
authors = "${author}"
displayURL = "${homepage}"
description = '''${description}'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.travelers_lantern]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc},${mc_next})"
ordering = "NONE"
side = "BOTH"
