modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "travelers_lantern"
version = "${version}"
displayName = "${name}"
authors = "${author}"
displayURL = "${homepage}"
description = '''${description}'''
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "travelers_lantern.mixins.json"

[[dependencies.travelers_lantern]]
modId = "minecraft"
type = "required"
versionRange = "[${mc},${mc_next})"
ordering = "NONE"
side = "BOTH"
